### ISSUE TITLE
Partition_problem.c

### ISSUE THREAD

**Issue by minseogang3** [2021-SIT-AdvancedAlgorithms/PA3_Partition_Problem#1]
![image](https://user-images.githubusercontent.com/91857599/141881109-32a68178-0976-4dcf-9748-01a4fab358f2.png)
 위 사진의 코드는 partition_problem.c 파일 안에 있는 코드인데 Github를 보면 Do not change라고 나와있습니다. 근데 코드 첫 번째 for문 안에서 sum을 {0,0}으로 초기화를 하지 않으면 첫 번째 for문에서 계속 sum이 증가합니다. Bug인지 feature인지 궁금합니다.

**Comment by minseogang3** [comment]
만약 bug라면, 첫 번째 for 문이 끝나고 두 번째 for 문이 시작되기 전에 sum을 {0,0}로 초기화해도 될까요?

**Comment by sungminlee114** [comment]
@minseogang3 버그입니다. 찾아주셔서 감사합니다. 

수정해주시고 풀 리퀘스트 날려주시면 Extra credit 5점 드리겠습니다.
