### ISSUE TITLE
함수 호출 전후 elements 순서

### ISSUE THREAD

**Issue by minseogang3** [2021-SIT-AdvancedAlgorithms/PA3_Partition_Problem#2]
혹시 partition_by_dp() 함수 호출 전후 elements 순서가 보존되어야 하나요? 함수 안에서 sort_elements()함수를 호출하면 오름차순으로 inplace되는데 다시 elements 순서를 return 하는 것이 맞나 싶어서요.

**Comment by sungminlee114** [comment]
관련해서 공지를 이슈에 올렸습니다.
