### ISSUE TITLE
두 부분집합을 구분하는 숫자의 순서

### ISSUE THREAD

**Issue by YSIT21013** [2021-SIT-AdvancedAlgorithms/PA3_Partition_Problem#3]
프로그램을 실행했을 때, 예로 {3, 5, 7, 5}가 있을 때, 0: {3, 7}, 1: {5, ,5}  와 0: {5, 5}, 1: {3, 7}를 찾는다면 하나만 남길 필요가 있나요?
![image](https://user-images.githubusercontent.com/91630452/143307155-ffd091a8-f853-4f2d-9447-feba00fd489d.png)

**Comment by sungminlee114** [comment]
하나만 남겨주세요
