### ISSUE TITLE
partition_problem.c

### ISSUE THREAD

**Issue by hye-1m** [2021-SIT-AdvancedAlgorithms/PA3_Partition_Problem#6]
partition_problem.c에서
printf("Sum of each group : [%d, %d]\n\n", sum[0], sum[1]); // Print to console

다음에 sum[0],sum[1]를  j에 대해 0으로 초기화 해주어야 할 것 같습니다.

**Comment by sungminlee114** [comment]
https://github.com/2021-SIT-AdvancedAlgorithms/PA3_Partition_Problem/issues/1#issue-1054346998

확인부탁드립니다.
